# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Brian Liston'
tagline:          'Blog'
description:      'The personal blog of <a href="http://brianliston.com">Brian Liston</a>.'
url:              http://brianliston.org

author:
  name:           'Brian Liston'
  url:            https://twitter.com/lliissttoonn

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/bpliston/blog
